{{- if .Values.images.backend.replicaCount }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: "{{ template "fullname" . }}-backend"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "backend"
spec:
    replicas: {{ .Values.images.backend.replicaCount }}
    selector:
        matchLabels:
            app: {{ template "name" . }}
            release: {{ .Release.Name }}
            component: "backend"
    template:
        metadata:
            labels:
                app: {{ template "name" . }}
                release: {{ .Release.Name }}
                component: "backend"
        spec:
            containers:
                -   name: "{{ .Chart.Name }}-backend"
                    image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag | default .Chart.Version }}"
                    imagePullPolicy: "{{ .Values.pullPolicy }}"
                    ports:
                        -   containerPort: {{ .Values.images.backend.servicePort }}
                            name: http
                        -   containerPort: 5701
                            name: hz1
                      {{- if or .Values.images.backend.debug .Values.images.backend.debugsuspend }}
                        -   containerPort: 5005
                            name: "jvm-debug"
                      {{- end }}
                    env:
                        -   name: JAVA_OPTS
                            value: "{{ .Values.images.backend.javaOpts }}{{ if .Values.images.backend.debug }} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005{{ end }}{{ if .Values.images.backend.debugsuspend }} -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005{{ end }}"
                        -   name: HAZELCAST_KUBERNETES_SERVICE
                            value: "{{ template "fullname" . }}-hzc"
                        -   name: HAZELCAST_KUBERNETES_NAMESPACE
                            value: "{{ .Release.Namespace }}"
                        -   name: ICURE_COUCHDB_URL
                            value: "{{ .Values.couchdbUrl }}:{{ .Values.couchdbPortNumber }}"
                        -   name: ICURE_COUCHDB_USERNAME
                            valueFrom:
                                secretKeyRef:
                                    key: username
                                    name: icure-couchdb-credentials
                        -   name: ICURE_COUCHDB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: password
                                    name: icure-couchdb-credentials

                        -   name: JWT_AUTH_PRIV_KEY
                            valueFrom:
                                secretKeyRef:
                                    key: authPriv
                                    name: icure-jwt-key

                        -   name: JWT_AUTH_PUB_KEY
                            valueFrom:
                                secretKeyRef:
                                    key: authPub
                                    name: icure-jwt-key

                        -   name: JWT_REFRESH_PRIV_KEY
                            valueFrom:
                                secretKeyRef:
                                    key: refreshPriv
                                    name: icure-jwt-key

                        -   name: JWT_REFRESH_PUB_KEY
                            valueFrom:
                                secretKeyRef:
                                    key: refreshPub
                                    name: icure-jwt-key

                      {{- range $key, $value := .Values.images.backend.env }}
                        -   name: "{{ $key }}"
                            value: "{{ $value }}"
                      {{- end }}
                    resources:
                        requests:
                            memory: {{ .Values.images.backend.memoryRequest | quote }}
                          {{- if .Values.images.backend.cpuRequest }}
                            cpu: {{ .Values.images.backend.cpuRequest | quote }}
                          {{- end }}
                        limits:
                            memory: {{ .Values.images.backend.memoryLimit | quote }}
                          {{- if .Values.images.backend.cpuLimit }}
                            cpu: {{ .Values.images.backend.cpuLimit | quote }}
                          {{- end }}
                    {{- if .Values.images.backend.readiness }}
                    readinessProbe:
                        httpGet:
                            path: /actuator/health/readiness
                            port: 16043
                        initialDelaySeconds: 20
                        periodSeconds: 10
                        timeoutSeconds: 5
                        successThreshold: 2
                        failureThreshold: 3
                    {{- end }}
                    {{- if .Values.images.backend.liveness }}
                    livenessProbe:
                        httpGet:
                            path: /actuator/health/liveness
                            port: 16043
                        initialDelaySeconds: 300
                        periodSeconds: 30
                        timeoutSeconds: 8
                        successThreshold: 1
                        failureThreshold: 3
                    {{- end }}
            imagePullSecrets:
                -   name: regsecret
{{- end }}
