{{- if .Values.tls }}
{{- $root := .Values }}
{{- range $serviceName, $ingress := .Values.images }}
{{- if eq (tpl ($ingress.condition | default "true") $) "true" }}
{{- if $ingress.virtualHosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "{{ template "fullname" $ }}-ingress-{{ $serviceName }}"
    annotations:
        {{- if $ingress.annotations }}
{{ toYaml $ingress.annotations | indent 8 }}
        {{- end }}
        {{- if $root.oldIngressApi }}
        kubernetes.io/ingress.class: {{ $root.ingressClassName }}
        {{- end }}
spec:
    {{- if not $root.oldIngressApi }}
    ingressClassName: {{ $root.ingressClassName }}
    {{- end }}
    tls:
        {{- range $root.tls }}
        -   secretName: {{ .secretName | default .refName }}
            {{- if .hosts }}
            hosts:
                {{- range .hosts }}
                -   {{ . }}
                {{- end }}
            {{- end }}
        {{- end }}
    rules:
        {{- range $ingress.virtualHosts }}
        {{- include "rules" (list $ $serviceName $ingress) | nindent 8 }}
            host: {{ . }}
        {{- end }}
---
{{- if $ingress.namespace }}
kind: Service
apiVersion: v1
metadata:
    name: "{{ $serviceName }}-from-{{ $ingress.namespace }}"
spec:
    type: ExternalName
    externalName: "{{ $serviceName }}.{{ $ingress.namespace }}.svc.cluster.local"
    ports:
        -   port: {{ $ingress.servicePort | default 80 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- define "rules" -}}
{{- $ := index . 0 }}
{{- $serviceName := index . 1 }}
{{- $ingress := index . 2 }}
-   http:
        paths:
            -   path: {{ $ingress.path | default "/" }}
                pathType: {{ $ingress.pathType | default "Prefix" }}
                backend:
                    service:
                        {{- if $ingress.namespace }}
                        name: "{{ $serviceName }}-from-{{ $ingress.namespace }}"
                        {{- else }}
                        name: {{ if $ingress.serviceName }}"{{ tpl $ingress.serviceName $ }}"{{else}}"{{ template "fullname" $ }}-{{ $serviceName }}"{{end}}
                        {{- end }}
                        port:
                            number: {{ $ingress.servicePort | default 80 }}
{{- end }}
