pullPolicy: "IfNotPresent"

couchdbUrl: "http://couchdb-svc-couchdb.couch"
couchdbPortNumber: 5984
couchdbVirtualHosts: ["couch.icure.dev"] # if couchdbUrl is an external URL, then this should be empty

ingressClassName: "haproxy"
#tls:
#    -   secretName: tls-example-com
#        hosts:
#            - one.example.com
#            - two.example.com

images:
    backend:
        repository: "docker.taktik.be/icure/icure-kraken"
        tag: "" # helm install
        replicaCount: 1
        javaOpts: "" # config
        memoryRequest: "4096M"
        memoryLimit: "4096M"
        cpuRequest: 100m
        cpuLimit: 2
        servicePort: 16043
        debug: true
        virtualHosts: []
        readiness: true
        liveness: true
        env:
            ICURE_COUCHDB_PREFIX: "icure-__"
            ICURE_COUCHDB_ENFORCE: "TRUE"
            ICURE_SYNC_GLOBAL_DATABASES: "TRUE"
            ICURE_MIKRONO_SUPERUSER: "icure"
            ICURE_MIKRONO_SUPERTOKEN: "" # config
            ICURE_MIKRONO_APPLICATIONTOKEN: "" # config
